apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kuberture.fullname" . }}
  labels:
    {{- include "kuberture.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
